spring:
  datasource:
    # 基本属性
    name: dev
    url: jdbc:mysql://192.168.190.129:3306/micro_service_business?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: 263385aA+
  # springCloud
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.190.129:8848
        ip:
  redis:
    database: 0
    host: 192.168.190.129
    port: 6379
    seconds: 43200
    jedis:
      pool:
        max-active: 1000
        max-wait: 10000
        max-idle: 100
        min-idle: 30
    timeout: 10000
    testOnBorrow: true
    testWhileIdle: true
    password: 9299
